#include <string>
#include <vector>
#include <iostream>
#include <sstream>
#include <utility>
#include <algorithm>
#include <exception>
#include <limits>
#include <fstream>
#include <cstdlib>
#include <iomanip>
#include <functional>
#include <tr1/unordered_set>
#include <queue>
#include <list>
